apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hlstatx-daemon-awards
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      activeDeadlineSeconds: 300
      template:
        spec:
          containers:
          - command:
            - docker-hlxce-awards
            env:
            - name: DB_HOST
              value: $DB_HOST
            - name: DB_NAME
              value: $DB_NAME
            - name: DB_PASSWORD
              value: $DB_PASSWORD
            - name: DB_USERNAME
              value: $DB_USERNAME
            image: registry.gitlab.com/nide.gg/docker-hlstatx-daemon:latest
            imagePullPolicy: Always
            name: hlstatx-daemon-awards
            resources: {}
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {}
              privileged: false
              readOnlyRootFilesystem: false
              runAsNonRoot: false
            stdin: true
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            tty: true
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 0 23 * * *
  successfulJobsHistoryLimit: 3
  suspend: false